name: Run tests

on: [push]

jobs:
  run-tests:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
      env:
        CI: true
